#Helper functions for shiny App for post analysis

make.data <- function(mat, cols, main.name="proportion",sdconst,extra.column=F)
{
  
  ## This function, generrates the data required for the box plot
  ##Inputs
    #Mat: is the matrix generated from reading all csv reportables
    #cols: are the columns to be used in boxplot
    # main.name: used for the column values, depending if it's a MFI or proportion
    #sdconst: is the sd factor to identify outliers
    # extra.column: is used to add the treatment information for the triplicate ( added Feb 2021)
  ## Output: 
  #a list with two data,frame, one to be the main data.frame to use for the boxplot, and one a data.frame of outliers
  mat2 <- as.matrix(mat[, cols])
  colnames(mat2) <- cols
  rownames(mat2) <- mat[,1]
  propmatrix <- stack(as.data.frame(mat2))
  propmatrix$file <- rownames(mat2)
  propmatrix$filesimple <- unlist(lapply(propmatrix$file,function(f1) unlist(strsplit(f1,":"))[1]))
  propmatrix$filesimple <- gsub(gsub(gsub(propmatrix$filesimple,pattern = "PANEL_A_",replacement = ""),
                                pattern = "_PANEL_A.fcs",replacement = ".fcs"),pattern = ".fcs",
                                replacement = "_PANEL_A.fcs")
  names(propmatrix) <- c(main.name,"population","file","filesimple")

  #remove empty rows
  propmatrix <-propmatrix[order(propmatrix$population,propmatrix$file,propmatrix$proportion),]
  delete <- which(propmatrix$population == "")
  if(length(delete) >0){
    propmatrix <- propmatrix[-delete,]
  }
  populationNumber <- length(unique(propmatrix$population))
  propmatrix$median <- ""
  propmatrix$mean <- ""
  propmatrix$sd <- ""
  if(extra.column)
  {
    propmatrix$median2 <- ""
    propmatrix$gr <- ""
    propmatrix$triplicate <-unlist(lapply(propmatrix$file,function(x) unlist(strsplit(x,".fcs_"))[2]))
    propmatrix$file <- sub(".fcs_[^_]+$", ".fcs",propmatrix$file)
    propmatrix$filesimple <- sub(".fcs_[^_]+$", ".fcs",propmatrix$filesimple)
   
    for (i in unique(propmatrix$triplicate))
    {
      for(j in unique(propmatrix$population)){
         ind1 <- which(propmatrix$triplicate==i &propmatrix$population==j )
         med <- median(x=as.numeric(propmatrix$proportion[ind1]))
         propmatrix$median2[ind1] <- med
         propmatrix$gr[ind1] <- paste(i,j,sep="_")
      }
    }
  }
  
  outlierpropmatrix <- propmatrix[1,]
  outlierpropmatrix[1,] <- NA
  idx <- 1
 
  for(i in unique(propmatrix$population)){
    if(i != ""){
      indices <- which(propmatrix$population==i)
      mean <- mean(x=as.numeric(propmatrix$proportion[indices]),na.rm=T)
      propmatrix$mean[indices] <- mean
      median <- median(as.numeric(propmatrix$proportion[indices]),na.r=T)
      propmatrix$median[indices] <- median
      sd <- sd(as.numeric(propmatrix$proportion[indices]),na.rm=T)
      propmatrix$sd[indices] <- sd
      upplim <- mean + sd*sdconst
      lowlim <- mean - sd*sdconst
      colnames(propmatrix)
      outliers <- which(as.numeric(propmatrix$proportion[indices]) > upplim)
      outliers <- append(outliers,values=which(as.numeric(propmatrix$proportion[indices]) < lowlim))
      if(length(outliers) >0){
        for(k in outliers){
          outlierpropmatrix[idx,] <- propmatrix[indices[k],]
          idx <- idx+1      
        }
      }
    }
  }
  
  if(outlierpropmatrix$population[1] == "" || is.na(outlierpropmatrix$population[1])){
    outlierpropmatrix <- outlierpropmatrix[-which(outlierpropmatrix$population==""),]
  }
  return(list(proportion=propmatrix,outlier=outlierpropmatrix))
}
####################################################
#this is the main plotting code for the interactive boxplot
##Inputs
  #alldata:  main data.frame of proportion generated by make.mat()
  #outlierdata: outlier data.frame generated by make.mat()
  #popstoplot: This is the vector of populationselected by the user in the Shiny app
  #name: used for labeling th y aixs, as it can be different on each boxplot (i.e., proportion, MFI, QC sums,...)
  #Show,mean: default is false, and it will be true, only if the boxplot_QC_Inter is seleced by the user
  #sample.ref: can be null or a sample selected by the user to be shown on the boxplot
#Output
# Interactive boxplot with clickable points
plot_results<- function(alldata,outlierdata,popstoplot=NULL,name,sample.ref=NULL){
  newdata <- alldata[1,]
  if (is.null(popstoplot))
    popstoplot <- as.vector(unique(alldata$population))
  for(i in 1:length(popstoplot)){
    newdata <- rbind(newdata,alldata[which(alldata$population==popstoplot[i]),])
  }
  alldata <- unique(newdata)
  lim1 <- floor(min(alldata$proportion,na.rm = T))
  lim2 <- ceiling(max(alldata$proportion,na.rm = T)+1)
  yname <- paste(name,"_n=",length(unique(dat$proportion$file)))
  #this is to scale the y-axis properly for both proportions and MFI
  by.factor <- ifelse(lim2>50,yes = 10,no=ifelse(lim2>30,yes = 5,no=ifelse(lim2>10,yes = 4,no = 2)))
  if (lim1>100 | lim2>1000)
    by.factor <- ifelse(lim2>2000,yes = 1000,no=ifelse(lim2>1000,yes = 500,no=ifelse(lim2>400,yes = 200,no = 100)))
  
  if(nrow(outlierdata) > 0 ){
    print("Outlier")
  
    r <- ggplot() +
      geom_boxplot_interactive(data=alldata,aes(x = population, y = proportion, colour=population),
                               show.legend = FALSE,outlier.shape=NA,na.rm=T)+
      geom_point_interactive(position=position_jitter(width=0.45,height=.45),size=.9,data=outlierdata,show.legend = FALSE,
                             aes(x = population, y = proportion,colour=population,
                                 tooltip=filesimple,data_id=filesimple))+
      
      scale_y_continuous(name=yname,limits = c(lim1,lim2),
                         breaks=seq(lim1,lim2,by=by.factor),expand=c(0,0))+
      xlab(label = "Population")
      theme(axis.text.x = element_text(angle = 60, hjust = 1,size=10),
            axis.text.y = element_text(hjust = 1, size=10,color=1),
            legend.position="none",plot.margin=unit(c(0.8,0,0,0.85),"cm"))
      if ( !is.null(sample.ref))
      {
        sample.ref <- paste(dirname(sample.ref),basename(sample.ref),sep="/:")
        which.ref <- which(alldata$file==sample.ref)
        refdata <- alldata[which.ref,]
        r <- r+geom_point_interactive(position=position_jitter(width=0.45,height=.45),size=2,data=refdata,show.legend = FALSE,
                                      aes(x = population, y = proportion,shape=factor(unlist(strsplit(filesimple,"_"))[2]),
                                          tooltip=filesimple,data_id=filesimple))
      } 
    
  }
  else if(length(outlierdata[,1])==0 & !is.null(sample.ref)){
    #When there is no outlier, but a reference sample is selected by the user
    print("No outlier and sample")
    sample.ref <- paste(dirname(sample.ref),basename(sample.ref),sep="/:")
   
      which.ref <- which(sub(".fcs_[^_]+$", ".fcs",alldata$file)==sample.ref)
  
    refdata <- alldata[which.ref,]
    r <- ggplot() +
      geom_boxplot_interactive(data=alldata,aes(x = population, y = proportion, colour=population),outlier.shape=NA,na.rm=T)+
      geom_point_interactive(position=position_jitter(width=0.45,height=.45),size=2,data=refdata,
                             aes(x = population, y = proportion,shape=factor(unlist(strsplit(filesimple,"_"))[2]),
                                 tooltip=filesimple,data_id=filesimple))+
      scale_y_continuous(name=yname,limits = c(lim1,lim2),breaks=seq(lim1,lim2,by=by.factor),expand=c(0,0))+
      xlab(label = "Population")+
      
      theme(axis.text.x = element_text(angle = 60, hjust = 1,size=10),
            axis.text.y = element_text(hjust = 1, size=10,color=1),
            legend.position="none",plot.margin=unit(c(0.8,0,0,0.85),"cm"))
   
  }else{
    print("No outlier and No sample")
    
  
    r <- ggplot() +
      geom_boxplot_interactive(data=alldata,aes(x = population, y = proportion, colour=population,
                                                tooltip=paste(population,", median = ",round(as.numeric(median),digits=2),
                                                              "%, mean = ",round(as.numeric(mean),digits=2),"%")),outlier.shape=NA,na.rm=T)+
      
      scale_y_continuous(name=yname,limits = c(lim1,lim2),breaks=seq(lim1,lim2,by=by.factor),expand=c(0,0))+
      xlab(label = "Population")+
      
      theme(axis.text.x = element_text(angle = 60, hjust = 1,size=10),
            axis.text.y = element_text(hjust = 1, size=10,color=1),
            legend.position="none",plot.margin=unit(c(0.8,0,0,0.85),"cm"))
   
    
  }
  
  return(r)
  
  
}

